<!--================Start Sign in  Area =================-->

	      <section class="industry">
	      	  <div class="container-fluid industry_main" style="background-color:#006477;">
	      	  	<div class="container">
	      	  	   <div class="row">
	      	  	   		<div class="col-12 col-md-6">
	      	  	   			<div class="industry_content mt-4">
	      	  	   				<h3>Bank and NBFC</h3>
	      	  	   				<p class="text-justify">Financial institutions, such as Banks and NBFCs, hold the most sensitive & personal dataset of a person than any other organization. This plentitude of data, including customer information, marketing campaigns, purchase history, & transactions has generated lucrative opportunities for them but also challenged the consistency of service and customer database management. Now, how do you effectually manage and distribute this data?</p>
	      	  	   				<a href="<?php echo base_url(); ?>contact-us" class=""><button class="btn btn-industry">Contact Us</button></a>
	      	  	   			</div>
	      	  	   		</div>
	      	  	   		<div class="col-12 col-md-6">
	      	  	   			<div class="">
	      	  	   				<img src="<?php echo base_url(); ?>assets/images/industry/new/Bank_and_NBFC.svg" alt="industry1" class="img-fluid">
	      	  	   			</div>
	      	  	   		</div>
	      	  	   		<h3></h3>
	      	  	   </div>
	      	  	 </div>
	      	  </div>
	      </section>


	      <section class="industry">
		        <div class="container">
		            <div class="row">
		                <div class="col-12 col-md-8 offset-md-2">
		                    <div class="text-center">
		                        <h2>Why choose FinCRM for <br>Banks & NBFC?</h2>
		                        <p class="text-center">Banking CRM software accrues customer data from a multitude of information sources at one platform. This integration of data and workforce helps enterprises to answer customers on a one-to-one basis and plan sturdy marketing campaign. A strong marketing campaign can be a superlative strategy for customer acquisition and higher revenue generation, if you know your audience. Comprehensive and potent banking CRM software can empower the entire workforce of financial institutions.</p>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </section>

		    <section class="industry">
		    	<div class="container web_view_industry">
		    		<div class="row animatable fadeInUp">
		            	 <div class="col-md-6">
		            	 	<div class="mt-4">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid pull-right" width="100%">
		            	 	</div>
		            	 </div>
		            	 <div class="col-md-6">
		            	 	<div class=" industry_content_features">
		            	 		<h3>Put Every Lead on Record using CRM</h3>
		            	 		<p class="text-justify">Banks and NBFCs have infinite amount of data of existing and prospective customers through email or digital marketing. FinCRM will allow you to visualize and share every detail with relevant users. It will enable you to allot a particular lead or opportunity to a specific team member for smooth communication over the whole cycle. All information, from the name to the amount of financial business done will be safely recorded in CRM system, which will lessen monotonous work and enhance productivity of every department. </p>
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-md-6">
		            	 	<div class=" industry_content_features pull-right">
		            	 		<h3>Level Up Task Management with CRM</h3>
		            	 		<p class="text-justify">In banks and NBFCs, there are different types of works, which are supposed to be done by various employees without discrepancy. FinCRM offers you a personalized section, where you can allot a task to the respective associate and keep a record of progress & output generated by him. You are allowed to set priority status of the task, i.e. low, normal, high, or urgent, which can help respective associate to manage the work schedule accordingly.</p>
		            	 	</div>
		            	 </div>
		            	 <div class="col-md-6">
		            	 	<div class="mt-4">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 </div>
		            </div>


		            <div class="row animatable fadeInUp">
		            	 <div class="col-md-6">
		            	 	<div class="mt-4">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid pull-right" width="100%">
		            	 	</div>
		            	 </div>
		            	 <div class="col-md-6">
		            	 	<div class="  industry_content_features">
		            	 		<h3>Reach Out to Every Prospect with SMS and Email Reminder</h3>
		            	 		<p class="text-justify">As a financial organization, banks and NBFCs have numerous products/services and a multitude of offers & discounts for new & existing customers over the time. You may also have to strike the chords of clients for repayments, service renewals, etc. To turn this chaotic task into a methodical process, a salient feature, CRM email and SMS reminder system, is offered by FinCRM to keep your marketing strategy sturdy. This feature enables you to schedule an email or SMS for respective clients at specific date & time about anything and optimize customer relationship management system. </p>
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-md-6">
		            	 	<div class="industry_content_features pull-right">
		            	 		<h3>Track Business Growth of every Branch and Business</h3>
		            	 		<p class="text-justify">In financial industry, there can be any number of branches of banks and NBFCs located at different locations but are being administered under one person. FinCRM provides you a pivotal reports feature to track progress in business of every branch in graphical form to better understand growth between any required dates on daily, monthly, or yearly basis. You can keep a track of individuals’ productivity and predict future sales pipeline directly from your desktop in just one go through merely one platform. </p>
		            	 	</div>
		            	 </div>
		            	 <div class="col-md-6">
		            	 	<div class="mt-4">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 </div>
		            </div>


		             <div class="row animatable fadeInUp">
		            	 <div class="col-md-6">
		            	 	<div class="mt-4">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid pull-right" width="100%">
		            	 	</div>
		            	 </div>
		            	 <div class="col-md-6">
		            	 	<div class="  industry_content_features">
		            	 		<h3>Uphold Privacy with Secure Document Manager</h3>
		            	 		<p class="text-justify">As already mentioned, banks & NBFCs possess and process a huge amount of consumer data and effectuate numerous marketing campaigns regularly. It becomes their responsibility to keep the customer information generated via various sources extremely safe and private. To assist you in this process, we will provide you a very secure and reliable document manager, wherein you can store all customer related documents inside the FinCRM itself. The document manager will only be accessed by authorized users to maintain security and privacy of data.</p>
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-md-6">
		            	 	<div class="industry_content_features pull-right">
		            	 		<h3>Put Operations in Order with Office Management Features</h3>
		            	 		<p class="text-justify">It is best of all when you get something extra with an investment. FinCRM is not only a customer data organizer but also a daily task and office manager. A worthwhile stake in FinCRM will bestow you with supplementary office organizer, where users can record their daily task and submit to their reporting authority directly through CRM software in just a few clicks just like a timesheet. We also allow user to attach files on which he/she has worked to let the higher authority know about the work progress and guide duly. </p>
		            	 	</div>
		            	 </div>
		            	 <div class="col-md-6">
		            	 	<div class="mt-4">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-md-6">
		            	 	<div class="mt-4">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid pull-right" width="100%">
		            	 	</div>
		            	 </div>
		            	 <div class="col-md-6">
		            	 	<div class="  industry_content_features">
		            	 		<h3>Go Above and Beyond with Knowledge Base</h3>
		            	 		<p class="text-justify">Financial industry launches new products, offers, and incentives regularly to captivate more customers. Before customers, your staff should have a better knowledge of offers to acquire prospects. FinCRM introduces Knowledge Base feature to share all the updates with workforce at one place. Now, you don’t need to send emails pertaining to the latest updates with each user in the organization and fast forward your operations. This CRM feature will help users to understand a big picture on a small screen to dramatically push the productivity. </p>
		            	 	</div>
		            	 </div>
		            </div>

		    	</div>


		    	<div class="container small_device_industry">
		    		<div class="row animatable fadeInUp">
		            	 <div class="col-12">
		            	 	<div class="mb-4 text-center">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 </div>
		            	 <div class="col-12">
		            	 	<div class="industry_content_features_mobile text-center">
		            	 		<h3>Put Every Lead on Record using CRM</h3>
		            	 		<p class="text-justify">Banks and NBFCs have infinite amount of data of existing and prospective customers through email or digital marketing. FinCRM will allow you to visualize and share every detail with relevant users. It will enable you to allot a particular lead or opportunity to a specific team member for smooth communication over the whole cycle. All information, from the name to the amount of financial business done will be safely recorded in CRM system, which will lessen monotonous work and enhance productivity of every department. </p>
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-12">
		            	 	<div class="mb-4 text-center">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 	
		            	 </div>
		            	 <div class="col-12">
		            	 	<div class="industry_content_features_mobile text-center">
		            	 		<h3>Level Up Task Management with CRM</h3>
		            	 		<p class="text-justify">In banks and NBFCs, there are different types of works, which are supposed to be done by various employees without discrepancy. FinCRM offers you a personalized section, where you can allot a task to the respective associate and keep a record of progress & output generated by him. You are allowed to set priority status of the task, i.e. low, normal, high, or urgent, which can help respective associate to manage the work schedule accordingly.</p>
		            	 	</div>
		            	 </div>
		            </div>


		            <div class="row animatable fadeInUp">
		            	 <div class="col-12">
		            	 	<div class="mb-4 text-center">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 </div>
		            	 <div class="col-12">
		            	 	<div class="industry_content_features_mobile text-center">
		            	 		<h3>Reach Out to Every Prospect with SMS and Email Reminder</h3>
		            	 		<p class="text-justify">As a financial organization, banks and NBFCs have numerous products/services and a multitude of offers & discounts for new & existing customers over the time. You may also have to strike the chords of clients for repayments, service renewals, etc. To turn this chaotic task into a methodical process, a salient feature, CRM email and SMS reminder system, is offered by FinCRM to keep your marketing strategy sturdy. This feature enables you to schedule an email or SMS for respective clients at specific date & time about anything and optimize customer relationship management system. </p>
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-12">
		            	 	<div class="mb-4 text-center">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 	
		            	 </div>
		            	 <div class="col-12">
		            	 	<div class="industry_content_features_mobile text-center">
		            	 		<h3>Track Business Growth of every Branch and Business</h3>
		            	 		<p class="text-justify">In financial industry, there can be any number of branches of banks and NBFCs located at different locations but are being administered under one person. FinCRM provides you a pivotal reports feature to track progress in business of every branch in graphical form to better understand growth between any required dates on daily, monthly, or yearly basis. You can keep a track of individuals’ productivity and predict future sales pipeline directly from your desktop in just one go through merely one platform. </p>
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-12">
		            	 	<div class="mb-4 text-center">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 </div>
		            	 <div class="col-12">
		            	 	<div class="industry_content_features_mobile text-center">
		            	 		<h3>Uphold Privacy with Secure Document Manager</h3>
		            	 		<p class="text-justify">As already mentioned, banks & NBFCs possess and process a huge amount of consumer data and effectuate numerous marketing campaigns regularly. It becomes their responsibility to keep the customer information generated via various sources extremely safe and private. To assist you in this process, we will provide you a very secure and reliable document manager, wherein you can store all customer related documents inside the FinCRM itself. The document manager will only be accessed by authorized users to maintain security and privacy of data.</p>
		            	 	</div>
		            	 </div>
		            </div>

		            <div class="row animatable fadeInUp">
		            	 <div class="col-12">
		            	 	<div class="mb-4 text-center">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 	
		            	 </div>
		            	 <div class="col-12">
		            	 	<div class="industry_content_features_mobile text-center">
		            	 		<h3>Put Operations in Order with Office Management Features</h3>
		            	 		<p class="text-justify">It is best of all when you get something extra with an investment. FinCRM is not only a customer data organizer but also a daily task and office manager. A worthwhile stake in FinCRM will bestow you with supplementary office organizer, where users can record their daily task and submit to their reporting authority directly through CRM software in just a few clicks just like a timesheet. We also allow user to attach files on which he/she has worked to let the higher authority know about the work progress and guide duly. </p>
		            	 	</div>
		            	 </div>
		            </div>

		             <div class="row animatable fadeInUp">
		            	 <div class="col-12">
		            	 	<div class="mb-4 text-center">
		            	 		<img src="<?php echo base_url(); ?>assets/images/industry/Finance_Consultant.svg" alt="industry1" class="img-fluid" width="100%">
		            	 	</div>
		            	 	
		            	 </div>
		            	 <div class="col-12">
		            	 	<div class="industry_content_features_mobile text-center">
		            	 		<h3>Go Above and Beyond with Knowledge Base</h3>
		            	 		<p class="text-justify">Financial industry launches new products, offers, and incentives regularly to captivate more customers. Before customers, your staff should have a better knowledge of offers to acquire prospects. FinCRM introduces Knowledge Base feature to share all the updates with workforce at one place. Now, you don’t need to send emails pertaining to the latest updates with each user in the organization and fast forward your operations. This CRM feature will help users to understand a big picture on a small screen to dramatically push the productivity. </p>
		            	 	</div>
		            	 </div>
		            </div>

		    	</div>
		    </section>


<section class="footer-content">
  <div class="container-fluid">
      <div class="row footer-top">
      	   <div class="col-lg-12 text-center pt-5 pb-5 ">
                <div class="header_section_demo pt-5 pb-5">
                	<h3 class="heading_1 text-white">Try FinCRM for yourself!</h3>
                	<p class="heading_2 text-white mt-4">Free with no long-term commitments for up to 15 Days</p>
                	<a href="<?php echo base_url(); ?>sign-up" class="btn try_for_free mt-4 mr-4">Try for free</a>
                	<a href="<?php echo base_url(); ?>request-for-demo" class="btn btn-footer mt-4">Request for demo</a>
	           </div>
	       </div>
      </div>
  </div>
  </section>



  <script type="text/javascript">
    

jQuery(function($) {
  
  // Function which adds the 'animated' class to any '.animatable' in view
  var doAnimations = function() {
    
    // Calc current offset and get all animatables
    var offset = $(window).scrollTop() + $(window).height(),
        $animatables = $('.animatable');
    
    // Unbind scroll handler if we have no animatables
    if ($animatables.length == 0) {
      $(window).off('scroll', doAnimations);
    }
    
    // Check all animatables and animate them if necessary
        $animatables.each(function(i) {
       var $animatable = $(this);
            if (($animatable.offset().top + $animatable.height() - 20) < offset) {
        $animatable.removeClass('animatable').addClass('animated');
            }
    });

    };
  
  // Hook doAnimations on scroll, and trigger a scroll
    $(window).on('scroll', doAnimations);
  $(window).trigger('scroll');

});
    </script>